version: '1'
services:
  backend_nodejs: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../.backend.env
  frontend_reactjs:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ../.frontend.env
    
